apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    env: prod
    app: main
    tier: frontend
    owner: vakhnenzon
spec:
  containers:
    - name : container-apache
      image: vakhnenzon/apaphp:latest
      ports:
        - containerPort: 80

    - name : container-tomcat
      image: vakhnenzon/tomcat:9.0
      ports:
        - containerPort: 8080
                